<script>

    function fun(){
        return new Promise((resp,rej)=>{
            setTimeout(() => {
                const err=true;
                if(!err){
                    console.log("obrigado por ajuda");
                    resp()
                }else{
                    console.log("desculpe por nada")
                    rej()
                }
                
            }, 3000);
        })
    }

    fun().then(()=>{
        console.log("Gracias Senhor")
    }).catch(()=>{
        console.log("Error Faustao")
    })
</script>